"""
Text provider fallback chain.

Builds the provider order from `config.ai_providers.fallback_order`,
skipping any provider whose API key isn't set in the environment, and
retries each provider a configurable number of times before moving on
to the next one. This is the only module the rest of the codebase
should import to generate text — it hides which provider/model
actually answered.
"""

from __future__ import annotations

import time

from config.logging_setup import get_logger
from config.settings import Config
from providers.base import ProviderError, RateLimitError, TextProvider
from providers.gemini_provider import GeminiTextProvider
from providers.groq_provider import GroqTextProvider
from providers.openrouter_provider import OpenRouterTextProvider

logger = get_logger(__name__)

_PROVIDER_CLASSES: dict[str, type] = {
    "gemini": GeminiTextProvider,
    "openrouter": OpenRouterTextProvider,
    "groq": GroqTextProvider,
}


class TextProviderChain:
    """Tries each configured, available text provider in order."""

    def __init__(self, cfg: Config) -> None:
        self._cfg = cfg
        self._providers: list[TextProvider] = []
        for provider_name in cfg.ai_providers.fallback_order:
            provider_cls = _PROVIDER_CLASSES.get(provider_name)
            if provider_cls is None:
                logger.warning("Unknown provider '%s' in fallback_order; skipping", provider_name)
                continue
            if not provider_cls.is_configured():
                logger.info("Provider '%s' has no API key set; skipping", provider_name)
                continue
            self._providers.append(provider_cls(cfg))

        if not self._providers:
            raise ProviderError(
                "No text providers are configured. Set at least one of "
                "GEMINI_API_KEY, OPENROUTER_API_KEY, or GROQ_API_KEY "
                "(see SETUP.md)."
            )

    def generate(self, prompt: str, *, max_tokens: int = 800) -> str:
        """Try each provider in order, with retries, until one succeeds."""
        last_error: Exception | None = None
        for provider in self._providers:
            attempts = self._cfg.ai_providers.max_retries_per_provider
            for attempt in range(1, attempts + 1):
                try:
                    result = provider.generate(prompt, max_tokens=max_tokens)
                    logger.info("Text generated by provider '%s'", provider.name)
                    return result
                except RateLimitError as exc:
                    logger.warning(
                        "Provider '%s' attempt %d/%d rate-limited: %s",
                        provider.name, attempt, attempts, exc,
                    )
                    last_error = exc
                    if attempt < attempts:
                        time.sleep(self._cfg.rate_limits.rate_limit_backoff_seconds)
                except Exception as exc:  # noqa: BLE001
                    logger.warning(
                        "Provider '%s' attempt %d/%d failed: %s",
                        provider.name, attempt, attempts, exc,
                    )
                    last_error = exc
                    if attempt < attempts:
                        time.sleep(self._cfg.ai_providers.retry_backoff_seconds)
        raise ProviderError(f"All text providers failed. Last error: {last_error}")
